### ISSUE TITLE
why gateway?

### ISSUE THREAD

**Issue by poopyi** [ezcGman/lora-gateway#3]
Hello, firstly, congratulations on the project. However, I didn't quite understand the title "gateway." You used E32 and E220 modules that use SX1278 and LLCC68 chips, but both of these are not gateways; they are simply LoRa transceivers. The gateway chip family belongs to the SX130x series.

**Comment by ezcGman** [comment]
Hey there,

thanks for the warm words :)

It's named "gateway" because it's technically / from a device/networks PoV a gateway :) It bridges LoRa to TCP / Ethernet / Wi-Fi.

Quote from wiki: "Gateway (telecommunications), a network node equipped for interfacing with another network that uses different communication protocols".

Hope that helps.
Greetings,

Andy!
